language: python
python:
    - "3.6"
services:
    - docker
before_install:
    - docker build -t draft-kings-fun .
script:
    - docker run draft-kings-fun flake8 .
    - docker run draft-kings-fun nosetests \
    draftfast.test.test_public_api draftfast.test.test_player_pool draftfast.test.test_csv_parse \
    --with-coverage --cover-package=.
